all:
	gcc -O3 -g -fPIC -std=c99 -Wall -Wextra -Wno-unused-parameter -shared -o ../libclib.so fluid.c images.c interface.c multiimgrotator.c particle.c random.c simulation.c topology.c transform.c -lSDL2 -lSDL2_image -lGLEW
