#!/bin/bash

sandbox_path=/home/sand/sandbox


cd $sandbox_path

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $BASE ]; then
    git pull
    killall main.py
    python ./main.py
fi

