#!/bin/bash

sandbox_path=/home/sand/sandbox-stable/sandbox

export DISPLAY=:0

cd $sandbox_path

git remote update

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")

if [ ! $LOCAL == $REMOTE ]; then
    git pull
    make
    killall -9 main.py
    python ./main.py &
fi

